### Signup
POST http://localhost:5254/api/auth/signup
Content-Type: application/json

{
    "email": "sohaibsalman@gmail.com",
    "password": "1234"
}


### Login
POST http://localhost:5254/api/auth/login
Content-Type: application/json

{
    "email": "sohaibsalman@gmail.com",
    "password": "1234"
}